name: Jekyll site CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Chmod
      run: cd app && chmod +x gradlew
    - name: Build wasmJsBrowserProductionWebpack
      run: cd app && ./gradlew wasmJsBrowserProductionWebpack
    - name: Move files
      run: cd app && mv composeApp/build/kotlin-webpack/wasmJs/productionExecutable/* ../docs/
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
    - uses: actions/jekyll-build-pages@v1
  deploy:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/deploy-pages@v4
