name: Jekyll site CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Chmod
      run: cd app && chmod +x gradlew
    - name: Build wasmJsBrowserProductionWebpack
      run: cd app && ./gradlew wasmJsBrowserProductionWebpack
    - name: Move files
      run: cd app && mv composeApp/build/kotlin-webpack/wasmJs/productionExecutable/* ../docs/
    - name: Setup Pages
      id: pages
      uses: actions/configure-pages@v5
    - name: Upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v3
  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    steps:
      - name: Deploy artifact
        id: deployment
        uses: actions/deploy-pages@v4
